services:
  riscv128:
    build: .
    user: "${USER_ID}:${GROUP_ID}"

    environment:
      USER: "${USER}"

    volumes:
      # Source directory which will contains code and built artifacts on the HOST
      - .:/work
