services:
  riscv128-toolchain:
    image: riscv128-toolchain
    build: .
    user: "${USER_ID}:${GROUP_ID}"

    environment:
      USER: "${USER}"

    volumes:
      # Source directory which will contains code and built artifacts on the HOST
      - .:/work
